apiVersion: apps/v1
kind: Deployment
metadata:
  name: miragex-app-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: miragex-app-controller
  template:
    metadata:
      labels:
        name: miragex-app-controller
    spec:
      serviceAccountName: miragex-app-controller-sa
      volumes:
        - name: app-volume
          emptyDir: {}
      initContainers:
        - name: git-clone
          image: alpine/git:v2.45.2
          command: ["sh", "-c"]
          args:
            - |
              # .git ディレクトリが既にあれば pull, なければ clone
              if [ -d "/app/.git" ]; then
                echo "Repository already exists. Pulling latest changes..."
                cd /app
                git pull
              else
                echo "Repository not found. Cloning..."
                git clone https://github.com/rassi0429/miragex.app /app
              fi
          volumeMounts:
            - name: "app-volume"
              mountPath: "/app"
      containers:
        - name: node-bot
          image: node:22
          imagePullPolicy: Always
          workingDir: /app
          command: ["bash", "-c"]
          args: ['npm install && npm run build && npm run start']
          volumeMounts:
            - name: "app-volume"
              mountPath: "/app"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: miragex-app-controller
  labels:
    app: miragex-app-controller
spec:
  type: ClusterIP
  selector:
    name: miragex-app-controller
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miragex-app-controller
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: neorb.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miragex-app-controller
                port:
                  number: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: miragex-app-controller-cluster-role
rules:
  # Deployments
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - "*"

  # Pods, Services
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - "*"

  # Ingress
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - "*"

  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: miragex-app-controller-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: miragex-app-controller-sa         # 紐付けたい ServiceAccount 名
    namespace: default       # 上記 ServiceAccount の Namespace
roleRef:
  kind: ClusterRole
  name: miragex-app-controller-cluster-role   # 上で作成した ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: miragex-app-controller-sa
  namespace: default
